# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e682dbc6497aa3a2fd42d93bcb6cdc03cd6fe1ad3bd32540dc5c9640b888e569046e544ad9f6fac44931af86f9c63a4a2c5fea25831b9ee470b94a3b25882f84

test:
  secret_key_base: 6aaa87e312ea181daef02497a089d48765fdf7af5efebbd954354b2ea401daac68efd4cab1acee5f128790675b906931953d37c45c0aa2d33944535e80777803

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
