interventions:
  vidange:
    name: "Vidange"
    price: 150.00
  revision:
    name: "Révision simple"
    price: 200.00
  vidange_complete:
   name: "Vidange + filtre"
   price: 180.00
  revision_generale:
   name: "Révision générale"
   price: 220.00

vehicles:
  renault:
    -
      name: clio

  peugeot:
    - name: 106



# @search = Search.new(intervention: "revision")

# @search.intervention # => "revision"

# Settings.interventions.public_send(@search.intervention).price


# class Toto
#    def call(arg1)
#       3  + arg1
#    end
# end


# myarg = 4
# instance = Toto.new
# instance.call(myarg)

# instance.public_send(:call, myarg)


