interventions:
  -
    name: "Vidange"
    price: 150.00
  -
    name: "Révision simple"
    price: 200.00
  -
   name: "Vidange + filtre"
   price: 180.00
  -
   name: "Révision générale"
   price: 220.00




vehicles:
  renault:
    -
      name: clio

  peugeot:
    - name: 106




